### ISSUE TITLE
unable to work with models on maas, critical error

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2361]
Juju GUI 2.2.7 on Juju 2.1beta4 on guimaas.

Loading the gui and getting the controller model (we should default to default as well?)

    combo?app/assets/javascripts/yui/lazy-model-list/lazy-model-list-min.js&app/assets/javascripts/yui/…:36 Uncaught TypeError: Cannot read property 'value' of undefined
        at f.maas.h.provider.modelGet.y (combo?app/assets/javascripts/yui/lazy-model-list/lazy-model-list-min.js&app/assets/javascripts/yui/…:36)
        at r.<anonymous> (combo?app/assets/javascripts/yui/lazy-model-list/lazy-model-list-min.js&app/assets/javascripts/yui/…:36)
        at r.dispatch_result (combo?app/assets/javascripts/yui/lazy-model-list/lazy-model-list-min.js&app/assets/javascripts/yui/…:36)
        at e.CustomEvent.u.fireComplex (combo?app/assets/javascripts/yui/oop/oop-min.js&app/assets/javascripts/yui/event-custom-base/event-…:9)
        at e.CustomEvent._fire (combo?app/assets/javascripts/yui/oop/oop-min.js&app/assets/javascripts/yui/event-custom-base/event-…:4)
        at r.fire (combo?app/assets/javascripts/yui/oop/oop-min.js&app/assets/javascripts/yui/event-custom-base/event-…:5)
        at r.on_message (combo?app/assets/javascripts/yui/widget-buttons/widget-buttons-min.js&app/assets/javascripts/yui/wi…:42)
        at WebSocket.h.onmessage (combo?app/store/env/bakery-min.js&app/jujulib/index-min.js&app/jujulib/charmstore-min.js&app/jujuli…:13)

In chatting with @hatched it seems that we're getting/not getting expected data from the maas provider connection in api.js. Line #817 in api.js was mentioned but that might be skewed based on what branch/code @hatched was looking at. 

After this error we're unable to go to the profile page and unable to create a new model at all. These error seems like the first step in validating the add-model will work as well. However, there might be more than one bug there.

**Comment by mitechie** [comment]
Pastebin of the websocket traffic

https://pastebin.canonical.com/177254/

**Comment by mitechie** [comment]
For this error verified that the ModelGet has lost the maas-server key. Filed a bug on Juju to add this back. 

https://bugs.launchpad.net/juju/+bug/1659612

For the GUI we need to be defensive when these keys change and catch things we have to have and flex when things we don't have to have are missing.

**Comment by mitechie** [comment]
The PR #2363 does help with the error during connection. However, I'm still unable to add a model successfully. 

In checking the additional failures:

    combo?app/assets/javascripts/yui/widget-position/widget-position-min.js&app/assets/javascripts/yui/…:35 Uncaught TypeError: Cannot read property 'map' of undefined
        at b._parseCloudResult (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…pp/assets/javascripts/yui/datasource-local/datasource-local-min.js:35:8160)
        at Object.keys.reduce (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…pp/assets/javascripts/yui/datasource-local/datasource-local-min.js:35:7263)
        at Array.reduce (native)
        at b._send_rpc.f (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…pp/assets/javascripts/yui/datasource-local/datasource-local-min.js:35:7204)
        at b.dispatch_result (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…app/assets/javascripts/yui/datasource-local/datasource-local-min.js:35:403)
        at e.CustomEvent.u.fireComplex (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…cape-min.js&app/assets/javascripts/yui/json-parse/json-parse-min.js:9:2397)
        at e.CustomEvent._fire (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…cape-min.js&app/assets/javascripts/yui/json-parse/json-parse-min.js:4:4519)
        at b.fire (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…cape-min.js&app/assets/javascripts/yui/json-parse/json-parse-min.js:5:5463)
        at b.on_message (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…pp/assets/javascripts/yui/datasource-local/datasource-local-min.js:33:2592)
        at WebSocket.h.onmessage (https://10.0.0.155:17070/gui/6351084b-2e9b-4934-8301-ac0f49f26bd2/4cf4170d9…et-min.js&app/jujulib/urls-min.js&app/jujulib/bakery-factory-min.js:15:980)
    _parseCloudResult @ combo?app/assets/javascripts/yui/widget-position/widget-position-min.js&app/assets/javascripts/yui/…:35
    Object.keys.reduce @ combo?app/assets/javascripts/yui/widget-position/widget-position-min.js&app/assets/javascripts/yui/…:35
    _send_rpc.f @ combo?app/assets/javascripts/yui/widget-position/widget-position-min.js&app/assets/javascripts/yui/…:35
    dispatch_result @ combo?app/assets/javascripts/yui/widget-position/widget-position-min.js&app/assets/javascripts/yui/…:35
    u.fireComplex @ combo?app/assets/javascripts/yui/oop/oop-min.js&app/assets/javascripts/yui/event-custom-base/event-…:9
    _fire @ combo?app/assets/javascripts/yui/oop/oop-min.js&app/assets/javascripts/yui/event-custom-base/event-…:4
    fire @ combo?app/assets/javascripts/yui/oop/oop-min.js&app/assets/javascripts/yui/event-custom-base/event-…:5
    on_message @ combo?app/assets/javascripts/yui/widget-position/widget-position-min.js&app/assets/javascripts/yui/…:33
    h.onmessage @ combo?app/state/state-min.js&app/store/env/bakery-min.js&app/jujulib/index-min.js&app/jujulib/charm…:15


Which looks like code: 

        _parseCloudResult: e=>{
            const f = e.regions.map(g=>{
                return {
                    name: g.name,
                    endpoint: g.endpoint || '',
                    identityEndpoint: g['identity-endpoint'] || '',
                    storageEndpoint: g['storage-endpoint'] || ''
                }
            }
            );


Which is expecting a regions to be there.

**Comment by mitechie** [comment]
I chased down some of this and it looks like lxd works because it presents a region of "localhost" where maas does not have a region. 

I've updated code to let region be optional and verified this code works on MAAS 2.1 on guimaas. 

#2365 is the hacked code there. I'm not sure if takes the full big picture into account and doesn't have tests atm.

**Comment by mitechie** [comment]
Hmm, it would seem to me that MAAS Zones should be regions here. We're not getting a list but maybe we or Juju are looking for the wrong field/attribute to determine what "regions" are in a MAAS world.

**Comment by mitechie** [comment]
In looking at https://docs.ubuntu.com/maas/2.1/en/intro-concepts#regions it seems that zones are more to an AZ and thus not in the running here for the region list. According to https://bugs.launchpad.net/juju/+bug/1600061 Juju isn't really doing much in the multi-region MAAS department at the moment so we'll just have to track that and make sure the Clouds api call responds with region info if Juju becomes more region aware in Juju.

**Comment by mitechie** [comment]
I'm going to EOD with this here. If someone wants to work on tests and complete in the morning peachy, otherwise I'll look to take up the branch and add tests when I'm back next week.

**Comment by mitechie** [comment]
Updated PR and putting up for review as the fix.
