### ISSUE TITLE
gisf: internal server error when trying to login and the beta is not opened

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2419]
When the GUI switch is only enabled under certain conditions, trying to log in from the storefront correctly points me to USSO, but after all credentials are provided, when being redirected to the storefront, an internal server error occurs, with the following traceback:
```
Traceback (most recent call last):
  File "/home/frankban/code/blues_browser/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/frankban/code/blues_browser/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/frankban/code/blues_browser/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/frankban/code/blues_browser/local/lib/python2.7/site-packages/pyramid/config/views.py", line 477, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/frankban/code/blues_browser/jaas_storefront/views/auth.py", line 225, in login_successful
    idm_payload
  File "/home/frankban/code/blues_browser/local/lib/python2.7/site-packages/theblues/identity_manager.py", line 68, in login
    timeout=self.timeout)
  File "/home/frankban/code/blues_browser/local/lib/python2.7/site-packages/theblues/utils.py", line 78, in make_request
    raise ServerError(err.response.status_code, msg)
ServerError: (401, 'Error during request: https://api.jujucharms.com/identity/v1/u/frankban message: {"message":"could not determine identity: invalid credentials","code":"unauthorized"}')
```

**Comment by jaycee** [comment]
This traceback is b/c the request was made with the production IdM, and development doesn't have the correct credentials for it. It's not an issue with the code, and on staging I can confirm that login for non beta is working.
